#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import samba
import sys

password_settings = samba.get_password_settings()

json.dump({
    "status": "success",
    "message": "password_policy",
    "policy": password_settings
}, fp=sys.stdout)
