#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

import samba

request = json.load(sys.stdin)

try:
    info = samba.get_user_password_expiration(os.environ["JWT_ID"])
except KeyError:
    json.dump(
        {
            "status": "failure",
            "message": "user_not_found",
            "expired": False,
            "expiration": None,
            "must_change": False,
        },
        fp=sys.stdout,
    )
    sys.exit(0)

json.dump(
    {
        "status": "success",
        "message": "password_expiration",
        **info,
    },
    fp=sys.stdout,
)
