#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# This script updates the api-moduled.env file contents
#

import sys
import agent

# Read the environment file as a dictionary
denv = agent.read_envfile("api-moduled.env")
orig_exports = denv.get("AMLD_EXPORT_ENV", "").split()
exports = orig_exports.copy()
if "PYTHONPATH" not in exports:
    exports.append("PYTHONPATH")
if "MODULE_ID" not in exports:
    exports.append("MODULE_ID")
if "DOMAIN" not in exports:
    exports.append("DOMAIN")
if orig_exports != exports:
    denv["AMLD_EXPORT_ENV"] = ' '.join(exports)
    # Write the updated environment back to the file
    agent.write_envfile("api-moduled.env", denv)
    print(f"AMLD_EXPORT_ENV updated", file=sys.stderr)
