#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import samba
import agent

request = json.load(sys.stdin)  # object with skip_existing + records list
skip_existing = request.get('skip_existing', False)
records = request.get('records', [])
progcbk = agent.get_progress_callback(1,99)
curprog = 0
def xprogcbk(p):
    global curprog
    v = int(p)
    if v > curprog:
        progcbk(v)
        curprog = v
success = samba.import_users(records, skip_existing, progfunc=xprogcbk)
if not success:
    sys.exit(1)
