#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import samba

request = json.load(sys.stdin)  # object with skip_existing + records list
skip_existing = request.get('skip_existing', False)
records = request.get('records', [])
samba.import_users(records, skip_existing)
